### ISSUE TITLE
Try to get all recipes of patch 3.15 via api

### ISSUE THREAD

**Issue by Ley21** [viion/XIVDB-API#1]
I try to get an json result for all recipes of 3.15. For this I try this request url:

http://api.xivdb.com/search?search=patch+3.15&filters=eyJieSI6ImJ5PW1haW4uaWQiLCJvbmUiOiJvbmU9cmVjaXBlcyIsIm9yZGVyIjoib3JkZXI9REVTQyIsInRleHQiOiJzdHJpbmc9cGF0Y2ggMy4xNSIsIndoZXJlIjoid2hlcmU9QU5EIn0=

**Comment by viion** [comment]
Hello,

You would use that filter string on the API, the base64 encoded is just for the site. For recipes under that patch it would be:

http://api.xivdb.com/search?one=recipes&where=AND&order=DESC&by=main.id&filters=patch=24&language=en

But this syntax will be changing when i release the new Search API, I will update here
