### ISSUE TITLE
Not found description of items or recipe

### ISSUE THREAD

**Issue by lcilpa** [viion/XIVDB-API#2]
Hello,

I can't find a column "description" anywhere in item or recipe.
Is there a way I can found those data ?
Thanks for your API btw, it's very complete (except missing craft).

**Comment by viion** [comment]
Hello!

Which item is missing craft? When I run: https://api.xivdb.com/item/16636/scintillant+staff I get 
```json
"craftable": [
        {
            "can_hq": 1,
            "can_quick_synth": 0,
            "class_name": "Goldsmith",
            "classjob": {
...
```

Or am I not understanding correctly?

As for description, this would be the `help` variable,

eg: https://api.xivdb.com/item/1675/curtana

```json
   "help": "One of the fabled relic weapons.",
    "help_cns": "\u4f20\u8bf4\u4e2d\u7684\u4e0a\u53e4\u6b66\u5668\u4e4b\u4e00\u3002",
    "help_de": "Eine der sagenumwobenen Reliktwaffen.",
    "help_en": "One of the fabled relic weapons.",
    "help_fr": "[Arme antique]",
    "help_ja": "[\u53e4\u306e\u6b66\u5668]",
```

**Comment by lcilpa** [comment]
Thank you very much for answer !
Yes it seems I have missing this part of the API, i haven't seen this on .md files, I hope there will be a doc (or I have missing that too).

Thanks again.
