### ISSUE TITLE
Python Script     if patch['patch'] == item['patch']: TypeError: string indices must be integers

### ISSUE THREAD

**Issue by toniohc** [viion/XIVDB-API#3]
I have a little trouble running your python script 😢 
When i run it, it display : 

>     if patch['patch'] == item['patch']:
> TypeError: string indices must be integers On line 52.

If i remove this section : 
```python
        for patch in patchList:
            if patch['patch'] == item['patch']:
                patchFolder = patch['command'] + '/'
```
No problem but all icon go in unknow. 
Can you please help me ? 😉

**Comment by viion** [comment]
Commited a fix, you can see it here: https://github.com/viion/XIVDB-API/commit/7c9a3ce96d18214b23af852475142004cd71e13f#diff-b2a451f314ba473d6bc6f70f133d2426L58

I've also uploaded another script that I use on XIVDB that doesn't use patch (as I don't need it). https://github.com/viion/XIVDB-API/blob/7c9a3ce96d18214b23af852475142004cd71e13f/Examples/Python/DownloadLodestoneIcons_2.md

**Comment by toniohc** [comment]
The one commited work very well :) 
I cannot run the second one. Maybe an error with my python setup.

`  File "C:\Users\DUMMY\Desktop\XIVDB\newscriptitems.py", line 31, in <module>
    patchResponse = http.urlopen(xivdbPatches)
  File "C:\Users\DUMMY\AppData\Local\Programs\Python\Python35\lib\urllib\request.py", line 163, in urlopen
    return opener.open(url, data, timeout)
  File "C:\Users\DUMMY\AppData\Local\Programs\Python\Python35\lib\urllib\request.py", line 472, in open
    response = meth(req, response)
  File "C:\Users\DUMMY\AppData\Local\Programs\Python\Python35\lib\urllib\request.py", line 582, in http_response
    'http', request, response, code, msg, hdrs)
  File "C:\Users\DUMMY\AppData\Local\Programs\Python\Python35\lib\urllib\request.py", line 510, in error
    return self._call_chain(*args)
  File "C:\Users\DUMMY\AppData\Local\Programs\Python\Python35\lib\urllib\request.py", line 444, in _call_chain
    result = func(*args)
  File "C:\Users\DUMMY\AppData\Local\Programs\Python\Python35\lib\urllib\request.py", line 590, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 404: Not Found`

**Comment by viion** [comment]
Oops, the second one has xivdb.dev instead of xivdb.com

Change that :)

**Comment by toniohc** [comment]
Now it run but the name of the file & folder are "broken". It's only number. 
IE : 
Folder : 1/2/3/4/5/6
In folder 1 : 1.png 10.png 11.png 113.png 199.png
In folder 3 : 3.png 300.png etc.

Don't worry, the other one work like a charm :smile:

**Comment by viion** [comment]
That is how it's meant to come out as it matches the game file data, where as names don't (e.g. There are two quicksilver items, very different items!) on xivdb I use item if for icons :)

**Comment by toniohc** [comment]
Ok Good to know 👍 
Thank you again and in this case, you can close the issue :smile:
